### ISSUE TITLE
A LIFX-only config?

### ISSUE THREAD

**Issue by jessicah** [rando-calrissian/Vela#6]
Is it possible to configure my install to only work with LIFX? I have two LIFX LED strips that I'd like to use. Also, does it recognize the addressable zones of LIFX strips?

**Comment by jessicah** [comment]
One other issue I seem to be coming across is that it expects ESP8266 to exist in configuration? I have changed the type to `Stripless` in `config.py`.

Getting the following trace, with the given logging added: `log( "Effect " + board + ": "+ key + " " + label + " " + ui_element, 4)` = `Effect ESP8266: width Scale slider`
```
Traceback (most recent call last):
  File "C:\Users\jessi\Vela\visualizer\python\main.py", line 2105, in <module>
    gui = GUI()
  File "C:\Users\jessi\Vela\visualizer\python\main.py", line 1051, in __init__
    self.initMainWindow()
  File "C:\Users\jessi\Vela\visualizer\python\main.py", line 1107, in initMainWindow
    self.addBoard(board)
  File "C:\Users\jessi\Vela\visualizer\python\main.py", line 1121, in addBoard
    self.initBoardUI(board)
  File "C:\Users\jessi\Vela\visualizer\python\main.py", line 1563, in initBoardUI
    self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setValue(config.settings["devices"][board]["effect_opts"][effect][key])
KeyError: 'width'
```
